name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # Trỏ đến thư mục gốc của dự án của bạn (đảm bảo có dấu / ở cuối)
          server-dir: /public_html/  # Thư mục đích trên máy chủ FTP của bạn (đảm bảo có dấu / ở cuối)
